#!/bin/bash

rm ~/lastRunProcIds2

current_date_time="`date +%Y-%m-%d`"
echo $current_date_time

current_source_dir=$HOME/projects/NE_UAScodes
cd $current_source_dir
source $current_source_dir/devel/setup.bash

mkdir -p $current_source_dir/logs
mkdir -p $current_source_dir/logs/Rhombi_Experiments

rm -rf $current_source_dir/logs/Rhombi_Experiments/images_latest
mkdir -p $current_source_dir/logs/Rhombi_Experiments/images_latest

mkdir -p $current_source_dir/logs/Rhombi_Experiments/$current_date_time
rm $current_source_dir/logs/Rhombi_Experiments/latest
ln -s $current_source_dir/logs/Rhombi_Experiments/$current_date_time $current_source_dir/logs/Rhombi_Experiments/latest

sleep 1s

roslaunch spinnaker_sdk_camera_driver acquisition.launch &
echo -n $! >> ~/lastRunProcIds2
echo -n " " >> ~/lastRunProcIds2

sleep 10s

#roslaunch logging_measurements rhombi_logger.launch &
#echo -n $! >> ~/lastRunProcIds2
#echo -n " " >> ~/lastRunProcIds2

#sleep 5s

#roslaunch rhombi_markers rhombi_detector.launch &
#echo -n $! >> ~/lastRunProcIds2
#echo -n " " >> lastRunProcIds2

#sleep 5s

echo "SEND CHARACTER TO START FYLING"
read varname

sleep 2s

roslaunch flight_pkg heading_check.launch &
echo -n $! >> ~/lastRunProcIds2
echo -n " " >> ~/lastRunProcIds2

read varname
echo "Exit character received"

for value in {1..2}
	do 
		echo "Stop attempt No." 
		echo $value
		rostopic pub -1 /experiment_execution std_msgs/Bool "data: false"
		rostopic pub -1 /experiment_logging std_msgs/Bool "data: false"
done

kill $(cat ~/lastRunProcIds2)
sleep 1s

echo "Done"
