#!/bin/bash

rm ~/lastRunProcIds

sleep 1s

current_source_dir=~/projects/NE_UAScodes
cd $current_source_dir
source $current_source_dir/devel/setup.bash

sleep 1s

#echo "Enter the sudo password, please"
#read PW

echo "NTP syncing"
echo q1w2 | sudo -S systemctl disable --now systemd-timesyncd
sleep 1s
echo q1w2 | sudo -S systemctl disable --now ntp
sleep 1s
echo q1w2 | sudo -S timedatectl set-local-rtc 1 --adjust-system-clock
sleep 1s
timedatectl set-local-rtc 1 --adjust-system-clock
sleep 1s
echo q1w2 | sudo -S ntpdate -bu 192.168.1.2
sleep 1s
echo "Clock synced"

roscore &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 3s

roslaunch mavros apm.launch fcu_url:="/dev/FCU:921600" &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 30s

rosrun mavros mavsys rate --all 25 &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 3s

roslaunch vrpn_client_ros sampleNE.launch &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 3s

roslaunch vrpn_relay vrpn_relay_v3.launch &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 3s

#rosrun flight_pkg setHome &
#echo -n $! >> ~/lastRunProcIds
#echo -n " " >> ~/lastRunProcIds

rosrun flight_pkg setHomeIndoor &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 5s

#python $current_source_dir/scripts/set_origin.py &
#echo -n $! >> ~/lastRunProcIds
#echo -n " " >> ~/lastRunProcIds

mkdir -p $current_source_dir/logs
mkdir -p $current_source_dir/logs/Leader_Follower

rm -rf $current_source_dir/logs/Leader_Follower/images_latest
mkdir -p $current_source_dir/logs/Leader_Follower/images_latest

mkdir -p $current_source_dir/logs/Leader_Follower/$current_date_time
rm $current_source_dir/logs/Leader_Follower/latest
ln -s $current_source_dir/logs/Leader_Follower/$current_date_time $current_source_dir/logs/Leader_Follower/latest

sleep 5s

#rosrun flight_pkg simple_takeoff_land &
#echo -n $! >> ~/lastRunProcIds2
#echo -n " " >> ~/lastRunProcIds2

#sleep 10s

roslaunch rhombi_markers rhombi_detector.launch &
echo -n $! >> ~/lastRunProcIds2
echo -n " " >> ~/lastRunProcIds2

sleep 2s

roslaunch spinnaker_sdk_camera_driver NE_acquisition_node_BW.launch &
echo -n $! >> ~/lastRunProcIds2
echo -n " " >> ~/lastRunProcIds2

sleep 2s

roslaunch logging_measurements leader_follower_logger.launch &
echo -n $! >> ~/lastRunProcIds2
echo -n " " >> ~/lastRunProcIds2

sleep 2s
#true to run, false to stop
rostopic pub -1 /grabbing_control std_msgs/Bool "data: true"
rostopic pub -1 /logger_control std_msgs/Bool "data: true"
#sleep 10s
#echo "Press button to start experiment"
#read varname
#sleep 15s
#rostopic pub -1 /experiment_control std_msgs/Bool "data: true"
#sleep 2s

echo "SEND CHARACTER TO STOP FYLING"
read varname
echo "Exit character received"


#for value in {1..5}
#	do 
#		echo "Stop attempt No." 
#		echo $value
#		rostopic pub /stop_execution std_msgs/Bool true
		rostopic pub -1 /experiment_control std_msgs/Bool "data: false"
		rostopic pub -1 /logger_control std_msgs/Bool "data: false"
		rostopic pub -1 /grabbing_control std_msgs/Bool "data: false"
#done

echo "EXITING!!!!!!"
sleep 5s 

kill $(cat ~/lastRunProcIds)
sleep 1s
killall roslaunch
sleep 1s
killall roscore
sleep 1s
killall rosrun
sleep 1s

echo "Done"
