#!/bin/bash

rm ~/lastRunProcIds

sleep 1s

current_source_dir=~/projects/NE_UAScodes
cd $current_source_dir
source $current_source_dir/devel/setup.bash

sleep 3s

roscore &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 3s

roslaunch mavros apm.launch fcu_url:="/dev/FCU:921600" &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 30s

rosrun mavros mavsys rate --all 25 &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

#sleep 5s

roslaunch vrpn_client_ros sample.launch server:=192.168.1.2 &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 5s

roslaunch vrpn_relay vrpn_relay.launch &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 5s

#rosrun flight_pkg setHome &
#echo -n $! >> ~/lastRunProcIds
#echo -n " " >> ~/lastRunProcIds

rosrun flight_pkg setHomeIndoor &
echo -n $! >> ~/lastRunProcIds
echo -n " " >> ~/lastRunProcIds

sleep 5s

#python $current_source_dir/scripts/set_origin.py &
#echo -n $! >> ~/lastRunProcIds
#echo -n " " >> ~/lastRunProcIds

echo "Press any key to exit..." &
read varname

#for value in {1..5}
#	do 
#		echo "Stop attempt No." 
#		echo $value
#		rostopic pub /stop_execution std_msgs/Bool true
#done

echo "EXITING!!!!!!"
sleep 5s 

kill $(cat ~/lastRunProcIds)
sleep 1s
killall roslaunch
sleep 1s
killall roscore
sleep 1s
killall rosrun
sleep 1s

echo "Done"
