#!/bin/bash
# My second script

current_source_dir=~/projects/nevangeliou_GapterUAV
cd $current_source_dir
source $current_source_dir/devel/setup.bash

sleep 2s

rosrun gps_measurements gps_measurements &
echo -n $! >> ~/lastRunProcIds_exp
echo -n " " >> ~/lastRunProcIds_exp

sleep 5s

echo "START FYLING"

rosrun flight_pkg simple_takeoff_land_outdoor &
echo -n $! >> ~/lastRunProcIds_exp
echo -n " " >> ~/lastRunProcIds_exp

read varname

echo "Exit character received"

for value in {1..2}
	do 
		echo "Stop attempt No." 
		echo $value
		rostopic pub /stop_experiment std_msgs/Bool "data: true"
done

sleep 10s

echo "Done"
